name: iOS Test Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build and Test default scheme using iPhone simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 13
        run: sudo xcode-select -switch /Applications/Xcode_13.3.app
      - name: iOS build setup
        run: >-
          xcodebuild test -workspace ChessTimeX.xcodeproj/project.xcworkspace -scheme ChessTimeXTests -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.4'

